[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nest-asyncio>=1.6.0",
    "python-telegram-bot==20.7",
    "telegram>=0.0.1",
    "trafilatura>=2.0.0",
    "twilio>=9.4.5",
]
